config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  
  get "home/items"  
  get "home/orders"
  get "home/account"
  get "home/products"
  get "home/customers"

  root to: "home#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :orders

  scope :order_, -> { includes(:orders).uniq.select("count(orders.id) orders_count, max(customer_id) as customer_id").group(:customer_id) } 

  def is_recurring_until date
    created_at.beginning_of_month.to_date == date.beginning_of_month.to_date
  end

  def recurring?(date)
    created_at.beginning_of_month.to_date != date.beginning_of_month.to_date
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :product_items
  has_many :products, through: :product_items
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :product

  belongs_to :customer

  enum status: [:daft, :confirmed, :canceled]

  scope :sold_products, -> { includes(product: :category).select("product_id, count(product_id) as sold_quantity").where(status: 1).group(:product_id) } 

  scope :by_week, -> (date_range) { where(created_at: date_range) }

  def self.month_data
    order_data = {}
    customer_ids = []   
    Order.all.each do |a|
      m_date = a.created_at  
      m_str = m_date.strftime("%b %Y")
      unless customer_ids.include? a.customer.id # TODO need to check this logic
        customer_ids << a.customer.id 
        customer_type =  a.customer.recurring?(m_date) ? "recurring" : "new"
        if order_data[m_str].nil?
          order_data[m_str] = [customer_type] 
        else
          order_data[m_str] << customer_type 
        end  
      end   
    end
    order_data_array = []  
    order_data.each do |key, val|
      new_count = val.select{ |v| v.eql? "new" }.count
      recurring_count = val.select{ |v| v.eql? "recurring" }.count
      order_data_array << {month: key,  reccuring_customer: recurring_count,  new_customer: new_count, total: val.count}
    end   
    order_data_array    
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  
  belongs_to :category

  has_many :orders
  has_many :product_items
  has_many :items, through: :product_items

end

app/models/product_item.rb
class ProductItem < ActiveRecord::Base
  
  belongs_to :item
  belongs_to :product

  scope :sold_items, -> { includes(:product, :item).select("max(product_id) as product_id,max(item_id) as item_id, sum(quantity) as sold_quantity").group(:item_id) } 

  scope :by_week, -> (date_range,customer) { where(product_id: customer.orders.by_week(date_range).pluck(:product_id)) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_customer!

  def index
    @orders = current_customer.orders.includes(product: :category).references(:product, :category).order('status ASC')
    #
    #
  end

  def account
    @orders = current_customer.orders.includes(product: :category).references(:product, :category).order('status ASC')
  end

  def orders
    @orders = current_customer.orders.includes(product: :category).references(:product, :category).order('status ASC')
  end

  def items
    unless params[:daterange].blank?
      from = params[:daterange].split(" - ")[0].to_date
      to = params[:daterange].split(" - ")[1].to_date
    else
      from = 1.weeks.ago
      to = Date.today
    end
    @product_items = ProductItem.by_week(from..to,current_customer).sold_items
  end

  def products
    unless params[:daterange].blank?
      from = params[:daterange].split(" - ")[0].to_date
      to = params[:daterange].split(" - ")[1].to_date
    else
      from = 1.weeks.ago
      to = Date.today
    end
    @orders = current_customer.orders.by_week(from..to).sold_products
  end

  def customers
    @total_orders = Order.count
    unless params[:daterange].blank?
      from = params[:daterange].split(" - ")[0].to_date
      to = params[:daterange].split(" - ")[1].to_date
      @orders = Order.by_week(from..to).group("customer_id").count.group_by{|key,val| val}.collect{|a,b| {a=>b.count}}.reduce Hash.new, :merge
    else
      @orders = Order.group("customer_id").count.group_by{|key,val| val}.collect{|a,b| {a=>b.count}}.reduce Hash.new, :merge
    end
    
    @month_data = Order.month_data
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_customer_orders.html.erb
<% @orders.each do |key,val| %>
  <tr>
    <th scope="row"><%=key %> Orders</th>
    <td><%= val %></td>
    <td><%= ((key*val)*100)/@total_orders rescue 0 %>%</td>
  </tr>
<% end %>

app/views/home/_items.html.erb
<% @product_items.each do |product_item| %>
  <tr>
    <th scope="row"><%= product_item.item.id %></th>
    <td><%= product_item.item.name %></td>
    <td><%= product_item.product.name %></td>
    <td><%= product_item.sold_quantity %></td>
  </tr>
<% end %>

app/views/home/_monthly_reccuring_customers.html.erb
<% @month_data.each do |order| %>
  <tr>
    <th scope="row"><%= order[:month] %></th>
    <td><%= order[:reccuring_customer] %></td>
    <td><%= order[:new_customer] %></td>
    <td><%= order[:total] %></td>
  </tr>
<% end %>

app/views/home/_products.html.erb
<% @orders.each do |order| %>
  <tr>
    <th scope="row"><%= order.product_id %></th>
    <td><%= order.product.name %></td>
    <td><%= order.product.category.name %></td>
    <td><%= order.sold_quantity %></td>
  </tr>
<% end %>

app/views/home/account.html.erb
<table class="table table-inverse table-bordered">
  <thead>
    <tr>
      <th>ORDER ID</th>
      <th>PRODUCT NAME</th>
      <th>PRODUCT CATEGORY</th>
      <th>STATUS</th>
      <th>ORDERED ON</th>
    </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
    <tr>
      <th scope="row"><%= order.id %></th>
      <td><%= order.product.name %></td>
      <td><%= order.product.category.name %></td>
      <td><%= order.status %></td>
      <td><%= order.created_at.strftime("%B %d, %Y") %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/home/customers.html.erb
<%= form_tag "/home/customers",method: :get,remote:true do  %>  
  <div class="container">    
    <div class="row">
      <div class="col-sm-6 form-group">
        <div class="input-group" id="DateDemo">
          <input type='text' name="daterange" id='weeklyDatePicker' placeholder="Select Week" />
        </div>
      </div>
    </div>
  </div>   
<% end %>
<table class="table table-inverse table-bordered">
  <thead>
    <tr>
      <th>Orders</th>
      <th>Customers</th>
      <th>Percentage</th>
    </tr>
  </thead>
  <tbody class="customers-orders">
    <%=render 'customer_orders'%>
  </tbody>
</table>

<table class="table table-inverse table-bordered">
  <thead>
    <tr>
      <th>Month</th>
      <th>Reccuring Customer</th>
      <th>New Customer</th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody class="reccuring-data">
    <%= render 'monthly_reccuring_customers'%>
  </tbody>
</table>
<script type="text/javascript">
  $('#weeklyDatePicker').datetimepicker({
    format: 'DD-MMM-YYYY'
  });
</script>

app/views/home/customers.js.erb
$(".customers-orders").html("<%=j render 'customer_orders' %>")

app/views/home/index.html.erb
<table class="table table-inverse table-bordered">
  <thead>
    <tr>
      <th>Orders</th>
      <th>Customers</th>
      <th>Percentage</th>
    </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
    <tr>
      <th scope="row"><%= order.id %></th>
      <td><%= order.product.name %></td>
      <td><%= order.product.category.name %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<table class="table table-inverse table-bordered">
  <thead>
    <tr>
      <th>Month</th>
      <th>Reccuring</th>
      <th>Customer</th>
      <th>New Customer</th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
    <tr>
      <th scope="row"><%= order.id %></th>
      <td><%= order.product.name %></td>
      <td><%= order.product.category.name %></td>
      <td><%= order.status %></td>
      <td><%= order.status %></td>
    </tr>
  <% end %>
  </tbody>
</table>

















<table class="table table-inverse table-bordered">
  <thead>
    <tr>
      <th>Orders</th>
      <th>Customers</th>
      <th>Percentage</th>
    </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
    <tr>
      <th scope="row"><%= order.id %></th>
      <td><%= order.product.name %></td>
      <td><%= order.product.category.name %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<table class="table table-inverse table-bordered">
  <thead>
    <tr>
      <th>Month</th>
      <th>Reccuring</th>
      <th>Customer</th>
      <th>New Customer</th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
    <tr>
      <th scope="row"><%= order.id %></th>
      <td><%= order.product.name %></td>
      <td><%= order.product.category.name %></td>
      <td><%= order.status %></td>
      <td><%= order.status %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/home/items.html.erb
<%= form_tag "/home/items",method: :get,remote:true do  %>  
  <div class="container">    
    <div class="row">
      <div class="col-sm-6 form-group">
          <div class="input-group" id="DateDemo">
            <input type='text' name="daterange" id='weeklyDatePicker' placeholder="Select Week" />
          </div>
      </div>
    </div>
  </div>   
<% end %>
   
<table class="table table-inverse table-bordered">
  <thead>
    <tr>
      <th>ITEM ID</th>
      <th>ITEM NAME</th>
      <th>PRODUCT NAME</th>
      <th>SOLD QUANTITY</th>
    </tr>
  </thead>
  <tbody class="items">
  <%=render 'items'%>
  </tbody>
</table>
<script type="text/javascript">
  $('#weeklyDatePicker').datetimepicker({
    format: 'DD-MMM-YYYY'
  });
</script>

app/views/home/items.js.erb
$(".items").html("<%=j render 'items' %>")

app/views/home/orders.html.erb
<table class="table table-inverse ">
  <thead>
    <tr>
      <th>ORDER ID</th>
      <th>PRODUCT NAME</th>
      <th>PRODUCT CATEGORY</th>
      <th>STATUS</th>
      <th>ORDERED ON</th>
    </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
    <tr>
      <th scope="row"><%= order.id %></th>
      <td><%= order.product.name %></td>
      <td><%= order.product.category.name %></td>
      <td><%= order.status %></td>
      <td><%= order.created_at.strftime("%B %d, %Y") %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/home/products.html.erb
<%= form_tag "/home/products",method: :get,remote:true do  %>  
  <div class="container">    
    <div class="row">
      <div class="col-sm-6 form-group">
        <div class="input-group" id="DateDemo">
          <input type='text' name="daterange" id='weeklyDatePicker' placeholder="Select Week" />
        </div>
      </div>
    </div>
  </div>   
<% end %>
<table class="table table-inverse table-bordered">
  <thead>
    <tr>
      <th>PRODUCT ID</th>
      <th>PRODUCT NAME</th>
      <th>PRODUCT CATEGORY</th>
      <th>SOLD QUANTITY</th>
    </tr>
  </thead>
  <tbody class="products">
    <%=render "products"%>
  </tbody>
</table>
<script type="text/javascript">
  $('#weeklyDatePicker').datetimepicker({
    format: 'DD-MMM-YYYY'
  });
</script>

app/views/home/products.js.erb
$(".products").html("<%=j render 'products' %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "E-Comm App", "/", class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse pull-right">
        <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Orders", home_orders_path %></li>
        <% if current_customer %>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Weekly
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Sold Products", home_products_path %></li>
            <li><%= link_to "Sold Items", home_items_path %></li>
            <li><%= link_to "Customers", home_customers_path %></li>
          </ul>
        </li>






          <li><%= link_to "Account", home_account_path %></li>
          <li><%= link_to "Log Out", destroy_customer_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Register", new_customer_registration_path %></li>
          <li><%= link_to "Log In", new_customer_session_path %></li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>